'use client'

import { motion } from 'framer-motion'
import {
  Compass,
  AlertTriangle,
  CheckCircle,
  Info,
  FileText,
} from 'lucide-react'
import { AdvisoryData, AdvisorySection } from '@/types'

interface AdvisoryDisplayProps {
  data: AdvisoryData
}

const priorityConfig = {
  high: {
    icon: AlertTriangle,
    borderColor: 'border-red-200',
    bgColor: 'bg-red-50',
    iconColor: 'text-red-500',
    badgeColor: 'bg-red-100 text-red-700',
  },
  medium: {
    icon: Info,
    borderColor: 'border-amber-200',
    bgColor: 'bg-amber-50',
    iconColor: 'text-amber-500',
    badgeColor: 'bg-amber-100 text-amber-700',
  },
  low: {
    icon: CheckCircle,
    borderColor: 'border-green-200',
    bgColor: 'bg-green-50',
    iconColor: 'text-green-500',
    badgeColor: 'bg-green-100 text-green-700',
  },
}

export function AdvisoryDisplay({ data }: AdvisoryDisplayProps) {
  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 px-5 py-4 text-white">
        <div className="flex items-center gap-2 mb-1">
          <Compass className="w-5 h-5" />
          <h3 className="text-lg font-bold">{data.destination}</h3>
        </div>
        {data.purpose && (
          <span className="inline-block px-2 py-0.5 bg-white/20 rounded-full text-xs mt-1">
            {data.purpose}
          </span>
        )}
      </div>

      {/* Summary */}
      {data.summary && (
        <div className="px-5 py-3 bg-gray-50 border-b border-gray-100">
          <p className="text-sm text-gray-600 leading-relaxed">{data.summary}</p>
        </div>
      )}

      {/* Sections */}
      <div className="p-4 space-y-3">
        {data.sections?.map((section: AdvisorySection, idx: number) => {
          const priority = section.priority || 'medium'
          const config = priorityConfig[priority]
          const Icon = config.icon

          return (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              className={`rounded-xl border ${config.borderColor} ${config.bgColor} p-4`}
            >
              <div className="flex items-start gap-3">
                <Icon className={`w-5 h-5 mt-0.5 flex-shrink-0 ${config.iconColor}`} />
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="text-sm font-semibold text-gray-900">{section.title}</h4>
                    <span className={`px-1.5 py-0.5 rounded text-[10px] font-medium ${config.badgeColor}`}>
                      {priority}
                    </span>
                  </div>
                  <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                    {section.content}
                  </p>
                </div>
              </div>
            </motion.div>
          )
        })}
      </div>

      {/* Footer */}
      <div className="px-5 py-3 bg-gray-50 border-t border-gray-100 flex items-center gap-2">
        <FileText className="w-3.5 h-3.5 text-gray-400" />
        <span className="text-xs text-gray-400">Generated by TripVerse AI</span>
      </div>
    </div>
  )
}
